<?php
    $sedes = [
        [
            "nombre" => "SEDECENTRAL",
            "direccion" => "C\\ATOCHA,405,MADRID"
        ],
        [
            "nombre" => "SEDESUR",
            "direccion" => "PLAZANUEVA,3,SEVILLA"
        ],
        [
            "nombre" => "SEDENORESTE",
            "direccion" => "PASEODEGRACIA,15,BARCELONA"
        ]
    ];

    $departamentos = [
        [
            "nombre" => "Financiero",
            "presupuesto" => 7350000,
            "sede_id" => 1
        ],
        [
            "nombre" => "RecursosHumanos",
            "presupuesto" => 1200000,
            "sede_id" => 1
        ],
        [
            "nombre" => "Marketing",
            "presupuesto" => 625000,
            "sede_id" => 2
        ],
        [
            "nombre" => "Comercial",
            "presupuesto" => 450000,
            "sede_id" => 3
        ],
        [
            "nombre" => "Compras",
            "presupuesto" => 2350000,
            "sede_id" => 2
        ],
        [
            "nombre" => "LogísticayOperaciones",
            "presupuesto" => 890000,
            "sede_id" => 3
        ],
        [
            "nombre" => "ControldeGestión",
            "presupuesto" => 350000,
            "sede_id" => 1
        ],
        [
            "nombre" => "Calidad",
            "presupuesto" => 140000,
            "sede_id" => 2
        ]
    ];

    $paises = [
        ["nacionalidad" => "Afgana", "pais" => "Afganistán"],
        ["nacionalidad" => "Albanesa", "pais" => "Albania"],
        ["nacionalidad" => "Alemana", "pais" => "Alemania"],
        ["nacionalidad" => "Andorrana", "pais" => "Andorra"],
        ["nacionalidad" => "Angoleña", "pais" => "Angola"],
        ["nacionalidad" => "Argelina", "pais" => "Argelia"],
        ["nacionalidad" => "Argentina", "pais" => "Argentina"],
        ["nacionalidad" => "Australiana", "pais" => "Australia"],
        ["nacionalidad" => "Austriaca", "pais" => "Austria"],
        ["nacionalidad" => "Bahamesa", "pais" => "Bahamas"],
        ["nacionalidad" => "Bahreina", "pais" => "Bahrein"],
        ["nacionalidad" => "Bangladesha", "pais" => "Bangladesh"],
        ["nacionalidad" => "Barbadesa", "pais" => "Barbados"],
        ["nacionalidad" => "Belga", "pais" => "Bélgica"],
        ["nacionalidad" => "Beliceña", "pais" => "Belice"],
        ["nacionalidad" => "Bermudesa", "pais" => "Bermudas"],
        ["nacionalidad" => "Birmana", "pais" => "Birmania"],
        ["nacionalidad" => "Boliviana", "pais" => "Bolivia"],
        ["nacionalidad" => "Botswanesa", "pais" => "Botswana"],
        ["nacionalidad" => "Brasileña", "pais" => "Brasil"],
        ["nacionalidad" => "Bulgara", "pais" => "Bulgaria"],
        ["nacionalidad" => "Burundesa", "pais" => "Burundi"],
        ["nacionalidad" => "Butana", "pais" => "Butan"],
        ["nacionalidad" => "Camboyana", "pais" => "RepdeCamboya"],
        ["nacionalidad" => "Camerunesa", "pais" => "Camerún"],
        ["nacionalidad" => "Canadiense", "pais" => "Canada"],
        ["nacionalidad" => "Centroafricana", "pais" => "RepCentroafricana"],
        ["nacionalidad" => "Chadeña", "pais" => "Chad"],
        ["nacionalidad" => "Checoslovaca", "pais" => "RepublicaCheca"],
        ["nacionalidad" => "Chilena", "pais" => "Chile"],
        ["nacionalidad" => "China", "pais" => "China"],
        ["nacionalidad" => "China", "pais" => "Taiwan"],
        ["nacionalidad" => "Chipriota", "pais" => "Chipre"],
        ["nacionalidad" => "Colombiana", "pais" => "Colombia"],
        ["nacionalidad" => "Congoleña", "pais" => "Congo"],
        ["nacionalidad" => "Costarricense", "pais" => "CostaRica"],
        ["nacionalidad" => "Cubana", "pais" => "Cuba"],
        ["nacionalidad" => "Danes", "pais" => "Dinamarca"],
        ["nacionalidad" => "Dominicana", "pais" => "RepublicaDominicana"],
        ["nacionalidad" => "Ecuatoriana", "pais" => "Ecuador"],
        ["nacionalidad" => "Egipcia", "pais" => "Egipto"],
        ["nacionalidad" => "Emirata", "pais" => "EmiratosArabes"],
        ["nacionalidad" => "Escosesa", "pais" => "Escocia"],
        ["nacionalidad" => "Eslovaca", "pais" => "Rep.Eslovaca"],
        ["nacionalidad" => "Española", "pais" => "España"],
        ["nacionalidad" => "Estona", "pais" => "Estonia"],
        ["nacionalidad" => "Etiope", "pais" => "Etiopia"],
        ["nacionalidad" => "Fijena", "pais" => "Fiji"],
        ["nacionalidad" => "Filipina", "pais" => "Filipinas"],
        ["nacionalidad" => "Finlandesa", "pais" => "Finlandia"],
        ["nacionalidad" => "Francesa", "pais" => "Francia"],
        ["nacionalidad" => "Gabiana", "pais" => "Gambia"],
        ["nacionalidad" => "Gabona", "pais" => "Gabón"],
        ["nacionalidad" => "Galesa", "pais" => "Gales"],
        ["nacionalidad" => "Ghanesa", "pais" => "Ghana"],
        ["nacionalidad" => "Granadeña", "pais" => "Granada"],
        ["nacionalidad" => "Griega", "pais" => "Grecia"],
        ["nacionalidad" => "Guatemalteca", "pais" => "Guatemala"],
        ["nacionalidad" => "GuinesaEcuatoriana", "pais" => "GuineaEcuatorial"],
        ["nacionalidad" => "Guinesa", "pais" => "Guinea"],
        ["nacionalidad" => "Guyanesa", "pais" => "Guyana"],
        ["nacionalidad" => "Haitiana", "pais" => "Haiti"],
        ["nacionalidad" => "Holandesa", "pais" => "Holanda"],
        ["nacionalidad" => "Hondureña", "pais" => "Honduras"],
        ["nacionalidad" => "Hungara", "pais" => "Hungria"],
        ["nacionalidad" => "India", "pais" => "India"],
        ["nacionalidad" => "Indonesa", "pais" => "Indonesia"],
        ["nacionalidad" => "Inglesa", "pais" => "Inglaterra"],
        ["nacionalidad" => "Iraki", "pais" => "Irak"],
        ["nacionalidad" => "Irani", "pais" => "Iran"],
        ["nacionalidad" => "Irlandesa", "pais" => "Irlanda"],
        ["nacionalidad" => "Islandesa", "pais" => "Islandia"],
        ["nacionalidad" => "Israeli", "pais" => "Israel"],
        ["nacionalidad" => "Italiana", "pais" => "Italia"],
        ["nacionalidad" => "Jamaiquina", "pais" => "Jamaica"],
        ["nacionalidad" => "Japonesa", "pais" => "Japón"],
        ["nacionalidad" => "Jordana", "pais" => "Jordania"],
        ["nacionalidad" => "Katensa", "pais" => "Katar"],
        ["nacionalidad" => "Keniana", "pais" => "Kenia"],
        ["nacionalidad" => "Kuwaiti", "pais" => "Kwait"],
        ["nacionalidad" => "Laosiana", "pais" => "Laos"],
        ["nacionalidad" => "Leonesa", "pais" => "Sierraleona"],
        ["nacionalidad" => "Lesothensa", "pais" => "Lesotho"],
        ["nacionalidad" => "Letonesa", "pais" => "Letonia"],
        ["nacionalidad" => "Libanesa", "pais" => "Libano"],
        ["nacionalidad" => "Liberiana", "pais" => "Liberia"],
        ["nacionalidad" => "Libeña", "pais" => "Libia"],
        ["nacionalidad" => "Liechtenstein", "pais" => "Liechtenstein"],
        ["nacionalidad" => "Lituana", "pais" => "Lituania"],
        ["nacionalidad" => "Luxemburgo", "pais" => "Luxemburgo"],
        ["nacionalidad" => "Madagascar", "pais" => "Madagascar"],
        ["nacionalidad" => "Malawi", "pais" => "Malawi"],
        ["nacionalidad" => "Maldivas", "pais" => "Maldivas"],
        ["nacionalidad" => "Mali", "pais" => "Mali"],
        ["nacionalidad" => "Maltesa", "pais" => "Malta"],
        ["nacionalidad" => "Marfilesa", "pais" => "CostadeMarfil"],
        ["nacionalidad" => "Marroqui", "pais" => "Marruecos"],
        ["nacionalidad" => "Mauricio", "pais" => "Mauricio"],
        ["nacionalidad" => "Mauritana", "pais" => "Mauritania"],
        ["nacionalidad" => "Mexicana", "pais" => "México"],
        ["nacionalidad" => "Monaco", "pais" => "Monaco"],
        ["nacionalidad" => "Mongolesa", "pais" => "Mongolia"],
        ["nacionalidad" => "Nauru", "pais" => "Nauru"],
        ["nacionalidad" => "Neozelandesa", "pais" => "NuevaZelandia"],
        ["nacionalidad" => "Nepalesa", "pais" => "Nepal"],
        ["nacionalidad" => "Nicaraguense", "pais" => "Nicaragua"],
        ["nacionalidad" => "Nigerana", "pais" => "Niger"],
        ["nacionalidad" => "Nigeriana", "pais" => "Nigeria"],
        ["nacionalidad" => "Norcoreana", "pais" => "CoreadelNorte"],
        ["nacionalidad" => "Norirlandesa", "pais" => "Irlandadelnorte"],
        ["nacionalidad" => "Norteamericana", "pais" => "EstadosUnidos"],
        ["nacionalidad" => "Noruega", "pais" => "Noruega"],
        ["nacionalidad" => "Omana", "pais" => "Omán"],
        ["nacionalidad" => "Pakistani", "pais" => "Pakistán"],
        ["nacionalidad" => "Panameña", "pais" => "Panamá"],
        ["nacionalidad" => "Paraguaya", "pais" => "Paraguay"],
        ["nacionalidad" => "Peruana", "pais" => "Perú"],
        ["nacionalidad" => "Polaca", "pais" => "Polonia"],
        ["nacionalidad" => "Portoriqueña", "pais" => "PuertoRico"],
        ["nacionalidad" => "Portuguesa", "pais" => "Portugal"],
        ["nacionalidad" => "Rhodesiana", "pais" => "Rhodesia"],
        ["nacionalidad" => "Ruanda", "pais" => "Ruanda"],
        ["nacionalidad" => "Rumana", "pais" => "Rumanía"],
        ["nacionalidad" => "Rusa", "pais" => "Rusia"],
        ["nacionalidad" => "Salvadoreña", "pais" => "ElSalvador"],
        ["nacionalidad" => "SamoaOccidental", "pais" => "SamoaOccidental"],
        ["nacionalidad" => "Sanmarino", "pais" => "SanMarino"],
        ["nacionalidad" => "Saudi", "pais" => "ArabiaSaudita"],
        ["nacionalidad" => "Senegalesa", "pais" => "Senegal"],
        ["nacionalidad" => "Singapur", "pais" => "Singapur"],
        ["nacionalidad" => "Siria", "pais" => "Siria"],
        ["nacionalidad" => "Somalia", "pais" => "Somalia"],
        ["nacionalidad" => "Sovietica", "pais" => "UnionSovietica"],
        ["nacionalidad" => "SriLanka", "pais" => "SriLanka(Ceylan)"],
        ["nacionalidad" => "Suazilandesa", "pais" => "Suazilandia"],
        ["nacionalidad" => "Sudafricana", "pais" => "Sudafrica"],
        ["nacionalidad" => "Sudanesa", "pais" => "Sudan"],
        ["nacionalidad" => "Sueca", "pais" => "Suecia"],
        ["nacionalidad" => "Suiza", "pais" => "Suiza"],
        ["nacionalidad" => "Surcoreana", "pais" => "CoreadelSur"],
        ["nacionalidad" => "Tailandesa", "pais" => "Tailandia"],
        ["nacionalidad" => "Tanzana", "pais" => "Tanzania"],
        ["nacionalidad" => "Tonga", "pais" => "Tonga"],
        ["nacionalidad" => "Tongo", "pais" => "Tongo"],
        ["nacionalidad" => "TrinidadyTobago", "pais" => "TrinidadyTobago"],
        ["nacionalidad" => "Tunecina", "pais" => "Tunez"],
        ["nacionalidad" => "Turca", "pais" => "Turquia"],
        ["nacionalidad" => "Ugandesa", "pais" => "Uganda"],
        ["nacionalidad" => "Uruguaya", "pais" => "Uruguay"],
        ["nacionalidad" => "Vaticano", "pais" => "Vaticano"],
        ["nacionalidad" => "Venezolana", "pais" => "Venezuela"],
        ["nacionalidad" => "Vietnamita", "pais" => "Vietnam"],
        ["nacionalidad" => "Yugoslava", "pais" => "Yugoslavia"],
        ["nacionalidad" => "Zaire", "pais" => "Zaire"]
    ];    
    
    $empleados = [
        ['nombre' => 'MiguelÁngel', 'email' => 'maperezes@email.com', 'apellidos' => 'PérezEstrada', 'salario' => 25000, 'hijos' => 4, 'departamento_id' => 1, 'pais_id' => 45],
        ['nombre' => 'Pilar', 'email' => 'pperezdi@email.com', 'apellidos' => 'PérezDíaz', 'salario' => 26000, 'hijos' => 1, 'departamento_id' => 1, 'pais_id' => 45],
        ['nombre' => 'Silvia', 'email' => 'sestevezpe@email.com', 'apellidos' => 'EstévezPérez', 'salario' => 27000, 'hijos' => 0, 'departamento_id' => 1, 'pais_id' => 45],
        ['nombre' => 'Teresa', 'email' => 'tserranoso@email.com', 'apellidos' => 'SerranoSosa', 'salario' => 28000, 'hijos' => 2, 'departamento_id' => 1, 'pais_id' => 45],
        ['nombre' => 'MaríaÁngeles', 'email' => 'madiazfe@email.com', 'apellidos' => 'DiezFernández', 'salario' => 29000, 'hijos' => 1, 'departamento_id' => 2, 'pais_id' => 45],
        ['nombre' => 'Pablo', 'email' => 'ptorreses@email.com', 'apellidos' => 'TorresEspinar', 'salario' => 30000, 'hijos' => 1, 'departamento_id' => 2, 'pais_id' => 45],
        ['nombre' => 'Manuel', 'email' => 'msolerame@email.com', 'apellidos' => 'SoleraMena', 'salario' => 31000, 'hijos' => 3, 'departamento_id' => 2, 'pais_id' => 45],
        ['nombre' => 'Joaquín', 'email' => 'jantonvi@email.com', 'apellidos' => 'AntónVillanueva', 'salario' => 32000, 'hijos' => 2, 'departamento_id' => 2, 'pais_id' => 45],
        ['nombre' => 'Alberto', 'email' => 'acarpinterolo@email.com', 'apellidos' => 'CarpinteroLópez', 'salario' => 18500, 'hijos' => 2, 'departamento_id' => 3, 'pais_id' => 45],
        ['nombre' => 'Juan', 'email' => 'jsantiagopi@email.com', 'apellidos' => 'SantiagoPintos', 'salario' => 19250, 'hijos' => 2, 'departamento_id' => 3, 'pais_id' => 45],
        ['nombre' => 'JuanJosé', 'email' => 'jjfernandezmo@email.com', 'apellidos' => 'FernándezMoreno', 'salario' => 20000, 'hijos' => 3, 'departamento_id' => 3, 'pais_id' => 45],
        ['nombre' => 'Pilar', 'email' => 'pgodoyse@email.com', 'apellidos' => 'GodoySerra', 'salario' => 20750, 'hijos' => 4, 'departamento_id' => 3, 'pais_id' => 45],
        ['nombre' => 'Francisca', 'email' => 'fgarciava@email.com', 'apellidos' => 'GarcíaValladares', 'salario' => 21500, 'hijos' => 3, 'departamento_id' => 3, 'pais_id' => 45],
        ['nombre' => 'MaríaMagdalena', 'email' => 'mmcastroma@email.com', 'apellidos' => 'CastroMarín', 'salario' => 22250, 'hijos' => 2, 'departamento_id' => 4, 'pais_id' => 45],
        ['nombre' => 'Manuel', 'email' => 'mfernandezfe@email.com', 'apellidos' => 'FernándezFernández', 'salario' => 23000, 'hijos' => 0, 'departamento_id' => 4, 'pais_id' => 45],
        ['nombre' => 'Luis', 'email' => 'lbarceloga@email.com', 'apellidos' => 'BarcelóGarcía', 'salario' => 23750, 'hijos' => 3, 'departamento_id' => 4, 'pais_id' => 45],
        ['nombre' => 'Jesús', 'email' => 'jlopezma@email.com', 'apellidos' => 'LópezMatías', 'salario' => 24500, 'hijos' => 4, 'departamento_id' => 4, 'pais_id' => 45],
        ['nombre' => 'Laura', 'email' => 'lnavarrofe@email.com', 'apellidos' => 'NavarroFernández', 'salario' => 28500, 'hijos' => 1, 'departamento_id' => 4, 'pais_id' => 45],
        ['nombre' => 'Sara', 'email' => 'sportillogo@email.com', 'apellidos' => 'PortilloGonzález', 'salario' => 29500, 'hijos' => 1, 'departamento_id' => 4, 'pais_id' => 45],
        ['nombre' => 'JuanManuel', 'email' => 'jmgallegoor@email.com', 'apellidos' => 'GallegoOrtiz', 'salario' => 30500, 'hijos' => 3, 'departamento_id' => 4, 'pais_id' => 45],
        ['nombre' => 'Carlos', 'email' => 'cdecastro@email.com', 'apellidos' => 'DeCastroMartínez', 'salario' => 31500, 'hijos' => 0, 'departamento_id' => 5, 'pais_id' => 45],
        ['nombre' => 'Andrea', 'email' => 'acrespo@email.com', 'apellidos' => 'CrespoGarcía', 'salario' => 32500, 'hijos' => 2, 'departamento_id' => 5, 'pais_id' => 45],
        ['nombre' => 'Rosa', 'email' => 'rgarciape@email.com', 'apellidos' => 'GarcíaPeinado', 'salario' => 33500, 'hijos' => 3, 'departamento_id' => 5, 'pais_id' => 45],
        ['nombre' => 'David', 'email' => 'dflores@email.com', 'apellidos' => 'FloresJiménez', 'salario' => 34500, 'hijos' => 2, 'departamento_id' => 5, 'pais_id' => 45],
        ['nombre' => 'Victoria', 'email' => 'vmartinez@email.com', 'apellidos' => 'MartínezBermúdez', 'salario' => 35500, 'hijos' => 4, 'departamento_id' => 5, 'pais_id' => 45],
        ['nombre' => 'Javier', 'email' => 'jquintero@email.com', 'apellidos' => 'QuinteroSánchez', 'salario' => 36500, 'hijos' => 1, 'departamento_id' => 6, 'pais_id' => 45],
        ['nombre' => 'Cristina', 'email' => 'cmartinez@email.com', 'apellidos' => 'MartínezGarcía', 'salario' => 37500, 'hijos' => 1, 'departamento_id' => 6, 'pais_id' => 45],
        ['nombre' => 'Antonio', 'email' => 'ajimenez@email.com', 'apellidos' => 'JiménezPérez', 'salario' => 38500, 'hijos' => 2, 'departamento_id' => 6, 'pais_id' => 45],
        ['nombre' => 'Ricardo', 'email' => 'rquiroga@email.com', 'apellidos' => 'QuirogaLópez', 'salario' => 39500, 'hijos' => 3, 'departamento_id' => 6, 'pais_id' => 45],
        ['nombre' => 'Elena', 'email' => 'egranado@email.com', 'apellidos' => 'GranadoFernández', 'salario' => 40500, 'hijos' => 2, 'departamento_id' => 6, 'pais_id' => 45],
        ['nombre' => 'LuisAntonio', 'email' => 'lrodriguez@email.com', 'apellidos' => 'RodríguezÁlvarez', 'salario' => 41500, 'hijos' => 4, 'departamento_id' => 6, 'pais_id' => 45],
        ['nombre' => 'Rafael', 'email' => 'rgonzalez@email.com', 'apellidos' => 'GonzálezMárquez', 'salario' => 42500, 'hijos' => 1, 'departamento_id' => 7, 'pais_id' => 45],
        ['nombre' => 'Miguel', 'email' => 'mperez@email.com', 'apellidos' => 'PérezFuentes', 'salario' => 43500, 'hijos' => 0, 'departamento_id' => 7, 'pais_id' => 45],
        ['nombre' => 'Inés', 'email' => 'ialvarez@email.com', 'apellidos' => 'ÁlvarezParedes', 'salario' => 44500, 'hijos' => 3, 'departamento_id' => 7, 'pais_id' => 45],
        ['nombre' => 'Raquel', 'email' => 'rdelgado@email.com', 'apellidos' => 'DelgadoVargas', 'salario' => 45500, 'hijos' => 2, 'departamento_id' => 7, 'pais_id' => 45],
        ['nombre' => 'Patricia', 'email' => 'ppardo@email.com', 'apellidos' => 'PardoMoreno', 'salario' => 46500, 'hijos' => 1, 'departamento_id' => 7, 'pais_id' => 45],
        ['nombre' => 'José', 'email' => 'jrodriguez@email.com', 'apellidos' => 'RodríguezHernández', 'salario' => 47500, 'hijos' => 0, 'departamento_id' => 7, 'pais_id' => 45],
        ['nombre' => 'Ángela', 'email' => 'agonzalez@email.com', 'apellidos' => 'GonzálezMartín', 'salario' => 48500, 'hijos' => 1, 'departamento_id' => 7, 'pais_id' => 45],
        ['nombre' => 'JoséAntonio', 'email' => 'jantonio@email.com', 'apellidos' => 'AntonioÁvila', 'salario' => 49500, 'hijos' => 2, 'departamento_id' => 8, 'pais_id' => 45],
        ['nombre' => 'Lourdes', 'email' => 'lmartin@email.com', 'apellidos' => 'MartínMárquez', 'salario' => 50500, 'hijos' => 3, 'departamento_id' => 8, 'pais_id' => 45],
        ['nombre' => 'Beatriz', 'email' => 'bfernandez@email.com', 'apellidos' => 'FernándezZamora', 'salario' => 51500, 'hijos' => 1, 'departamento_id' => 8, 'pais_id' => 45],
        ['nombre' => 'Carmen', 'email' => 'cmartin@email.com', 'apellidos' => 'MartínVázquez', 'salario' => 52500, 'hijos' => 3, 'departamento_id' => 8, 'pais_id' => 45],
        ['nombre' => 'Julio', 'email' => 'jhuerta@email.com', 'apellidos' => 'HuertaSánchez', 'salario' => 53500, 'hijos' => 2, 'departamento_id' => 8, 'pais_id' => 45],
        ['nombre' => 'Alicia', 'email' => 'amurillo@email.com', 'apellidos' => 'MurilloVera', 'salario' => 54500, 'hijos' => 0, 'departamento_id' => 8, 'pais_id' => 45]
    ];
        
?>